version: "2.39.2"

services:
  bot_longpolling:
    build:
      context: .
    restart: on-failure
    volumes:
      - ./logs:/bot/logs
      - ./src:/bot/src
    env_file:
      - ./.env
    depends_on:
      - db
  bot_webhook:
    build:
      context: .
    command:
      - "fastapi"
      - "dev"
      - "--host"
      - "0.0.0.0"
      - "src/webhook.py"
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ./logs:/bot/logs
      - ./src:/bot/src
    env_file:
      - ./.env
    depends_on:
      - db
      - ngrok
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bot
    ports:
      - 5432:5432
    volumes:
      - botdata:/var/lib/postgresql/data
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "http://host.docker.internal:8000"
      - "--url"
      - "https://biocentric-sherrill-glamorously.ngrok-free.dev"
    ports:
      - 4040:4040
    env_file:
      - ./.env


    
volumes:
  botdata: