[project]
name = "aiogram-timepicker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Steven Rudenko", email = "steven.gucum@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.22.0",
    "pydantic>=2.11.9",
    "pytz>=2025.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
